#version 330 core

in vec2 textureCoords;
in float fogVisibility;

uniform sampler2D texture;
uniform vec3 fogColor;

out vec4 color;

vec4 ApplyFog(vec4 color)
{
	return mix(vec4(fogColor, 1.0f), color, fogVisibility);
}

void main()
{
    vec4 MaterialDiffuseColor = texture2D(texture, textureCoords);

	if(MaterialDiffuseColor.a < 0.5)
	{
		discard;
	}
	color = MaterialDiffuseColor;

	color = ApplyFog(color);
}